%PYTHON_27% colorSchemeTool.py "tmThemes\Active4D.tmTheme" "intellijThemes\Active4D.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\All Hallow's Eve.tmTheme" "intellijThemes\All Hallow's Eve.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Amy.tmTheme" "intellijThemes\Amy.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Blackboard.tmTheme" "intellijThemes\Blackboard.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Cobalt.tmTheme" "intellijThemes\Cobalt.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Dawn.tmTheme" "intellijThemes\Dawn.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Eiffel.tmTheme" "intellijThemes\Eiffel.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Espresso Libre.tmTheme" "intellijThemes\Espresso Libre.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\IDLE.tmTheme" "intellijThemes\IDLE.icls"
::%PYTHON_27% colorSchemeTool.py "tmThemes\LAZY.tmTheme" "intellijThemes\LAZY.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Mac Classic.tmTheme" "intellijThemes\Mac Classic.icls"
::%PYTHON_27% colorSchemeTool.py "tmThemes\MagicWB (Amiga).tmTheme" "intellijThemes\MagicWB (Amiga).icls"
::%PYTHON_27% colorSchemeTool.py "tmThemes\Monokai Bright.tmTheme" "intellijThemes\Monokai Bright.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Monokai.tmTheme" "intellijThemes\Monokai.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Pastels on Dark.tmTheme" "intellijThemes\Pastels on Dark.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Railscasts.tmTheme" "intellijThemes\Railscasts.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Slush & Poppies.tmTheme" "intellijThemes\Slush & Poppies.icls"
::%PYTHON_27% colorSchemeTool.py "tmThemes\SpaceCadet.tmTheme" "intellijThemes\SpaceCadet.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Sunburst.tmTheme" "intellijThemes\Sunburst.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\Twilight.tmTheme" "intellijThemes\Twilight.icls"
::%PYTHON_27% colorSchemeTool.py "tmThemes\Zenburnesque.tmTheme" "intellijThemes\Zenburnesque.icls"
%PYTHON_27% colorSchemeTool.py "tmThemes\iPlastic.tmTheme" "intellijThemes\iPlastic.icls"
