%PYTHON_27% colorSchemeTool.py "tmThemes\Active4D.tmTheme" "intellijThemes\Active4D.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\All Hallow's Eve.tmTheme" "intellijThemes\All Hallow's Eve.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Amy.tmTheme" "intellijThemes\Amy.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Blackboard.tmTheme" "intellijThemes\Blackboard.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Cobalt.tmTheme" "intellijThemes\Cobalt.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Dawn.tmTheme" "intellijThemes\Dawn.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Eiffel.tmTheme" "intellijThemes\Eiffel.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Espresso Libre.tmTheme" "intellijThemes\Espresso Libre.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\IDLE.tmTheme" "intellijThemes\IDLE.xml"
::%PYTHON_27% colorSchemeTool.py "tmThemes\LAZY.tmTheme" "intellijThemes\LAZY.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Mac Classic.tmTheme" "intellijThemes\Mac Classic.xml"
::%PYTHON_27% colorSchemeTool.py "tmThemes\MagicWB (Amiga).tmTheme" "intellijThemes\MagicWB (Amiga).xml"
::%PYTHON_27% colorSchemeTool.py "tmThemes\Monokai Bright.tmTheme" "intellijThemes\Monokai Bright.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Monokai.tmTheme" "intellijThemes\Monokai.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Pastels on Dark.tmTheme" "intellijThemes\Pastels on Dark.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Railscasts.tmTheme" "intellijThemes\Railscasts.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Slush & Poppies.tmTheme" "intellijThemes\Slush & Poppies.xml"
::%PYTHON_27% colorSchemeTool.py "tmThemes\SpaceCadet.tmTheme" "intellijThemes\SpaceCadet.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Sunburst.tmTheme" "intellijThemes\Sunburst.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\Twilight.tmTheme" "intellijThemes\Twilight.xml"
::%PYTHON_27% colorSchemeTool.py "tmThemes\Zenburnesque.tmTheme" "intellijThemes\Zenburnesque.xml"
%PYTHON_27% colorSchemeTool.py "tmThemes\iPlastic.tmTheme" "intellijThemes\iPlastic.xml"
